language: objective-c
osx_image: xcode10
install:
- swift package update
- swift package generate-xcodeproj --enable-code-coverage
script:
- xcodebuild test -workspace SwiftKotlin.xcworkspace -scheme SwiftKotlinFramework
